name: Publish to NPM

on:
  push:
    branches: [ "master" ]

jobs:
  publish-npm:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
