name: Publish to NPM

on:
  push:
    branches: [ "master" ]

jobs:
  publish-npm:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
